-- Migration to add knowledge base passages table for RAG system
-- NOTE: Table creation is now handled idempotently in 0000.
-- This migration is now purely about seeding data.

-- Add some sample knowledge base passages for ALiEM cases
INSERT INTO "kb_passages" ("case_id", "stage", "section", "tags", "text", "source_citation", "license", "document_id", "passage_hash") VALUES
('aliem_case_01_anaphylaxis', 1, 'critical_actions', '["critical_actions","airway","anaphylaxis","ICS1"]', 'In anaphylaxis, immediately assess airway, breathing, and circulation. Administer IM epinephrine 0.01 mg/kg (max 0.3 mg) in the anterolateral thigh. Establish IV access and prepare for potential intubation if airway compromise occurs.', 'ALiEM ReSCu Peds - Case 1: Anaphylaxis - Critical Actions', 'CC BY-NC-SA 4.0', 'aliem-rescu-peds-2021', 'hash_001'),
('aliem_case_01_anaphylaxis', 1, 'objectives', '["objectives","anaphylaxis","recognition"]', 'Recognize signs of anaphylaxis: facial swelling, difficulty breathing, wheezing, hypotension, tachycardia, urticaria. Understand the urgency of immediate epinephrine administration.', 'ALiEM ReSCu Peds - Case 1: Anaphylaxis - Learning Objectives', 'CC BY-NC-SA 4.0', 'aliem-rescu-peds-2021', 'hash_002'),
('aliem_case_01_anaphylaxis', 2, 'critical_actions', '["critical_actions","medication","anaphylaxis","ICS2"]', 'After epinephrine, administer IV fluids bolus 20 mL/kg for hypotension. Give diphenhydramine IV 1 mg/kg (max 50 mg) and ranitidine IV 1 mg/kg (max 50 mg). Consider nebulized albuterol for bronchospasm.', 'ALiEM ReSCu Peds - Case 1: Anaphylaxis - Stage 2 Actions', 'CC BY-NC-SA 4.0', 'aliem-rescu-peds-2021', 'hash_003'),
('aliem_case_02_cardiac_tamponade', 1, 'critical_actions', '["critical_actions","cardiac","tamponade","ICS1"]', 'In cardiac tamponade, immediately assess for Beck''s triad: hypotension, muffled heart sounds, and distended neck veins. Prepare for emergency pericardiocentesis. Administer IV fluids to maintain preload.', 'ALiEM ReSCu Peds - Case 2: Cardiac Tamponade - Critical Actions', 'CC BY-NC-SA 4.0', 'aliem-rescu-peds-2021', 'hash_004'),
('aliem_case_02_cardiac_tamponade', 1, 'objectives', '["objectives","cardiac","tamponade","recognition"]', 'Recognize signs of cardiac tamponade: chest pain, dyspnea, tachycardia, hypotension, muffled heart sounds, pulsus paradoxus. Understand the need for immediate pericardiocentesis.', 'ALiEM ReSCu Peds - Case 2: Cardiac Tamponade - Learning Objectives', 'CC BY-NC-SA 4.0', 'aliem-rescu-peds-2021', 'hash_005')
ON CONFLICT DO NOTHING;
